### ISSUE TITLE
Memcached expiry test fails

### ISSUE THREAD

**Issue by penberg** [scylladb/seastar#130]
The expiry test for ``memcached`` fails as follows:

```
[penberg@nero seastar]$ tests/memcached/test.py --mode release
Memcached started.
Running: tests/memcached/test_memcached.py
seastar memcached v1.0
.......F.........................
======================================================================
FAIL: test_expiry_at_epoch_time (__main__.TestCommands)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/memcached/test_memcached.py", line 51, in wrapper
    return f(self)
  File "tests/memcached/test_memcached.py", line 262, in test_expiry_at_epoch_time
    self.assertEqual(call('get key\r\n'), b'VALUE key 0 5\r\nhello\r\nEND\r\n')
AssertionError: b'END\r\n' != b'VALUE key 0 5\r\nhello\r\nEND\r\n'

----------------------------------------------------------------------
Ran 33 tests in 18.840s

FAILED (failures=1)
Killing memcached...
Memcached killed.
Traceback (most recent call last):
  File "tests/memcached/test.py", line 46, in <module>
    run(args, [])
  File "tests/memcached/test.py", line 33, in run
    subprocess.check_call(cmdline)
  File "/usr/lib64/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tests/memcached/test_memcached.py']' returned non-zero exit status 1
```

Reverting 02b5313120b4e844c3b747e53ada5736ca94ce4a fixes the problem.

**Comment by penberg** [comment]
Ping @asias @vladzcloudius
