### ISSUE TITLE
Seastar.app.memcached.memcached fails randomly

### ISSUE THREAD

**Issue by tchaikov** [scylladb/seastar#1476]
```
73/74 Test #73: Seastar.app.memcached.memcached ...............***Failed   35.76 sec
[0/1] cd /home/circleci/project/build/debug/apps/memcached/tests && /home/circleci/project/apps/memcached/tests/test.py --memcached /home/circleci/project/build/debug/apps/memcached/memcached
WARNING: debug mode. Not for benchmarking or production
INFO  2023-02-06 04:05:46,872 seastar - Reactor backend: linux-aio
WARN  2023-02-06 04:05:46,872 [shard 0] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
INFO  2023-02-06 04:05:46,875 [shard 0] seastar - Created fair group io-queue-0, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000
INFO  2023-02-06 04:05:46,875 [shard 0] seastar - IO queue uses 0.75ms latency goal for device 0
INFO  2023-02-06 04:05:46,875 [shard 0] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
INFO  2023-02-06 04:05:46,875 [shard 0] seastar - Created io queue dev(0) capacities: 512:2000:2000 1024:3000:3000 2048:5000:5000 4096:9000:9000 8192:17000:17000 16384:33000:33000 32768:65000:65000 65536:129000:129000 131072:257000:257000
WARN  2023-02-06 04:05:46,876 [shard 1] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
.................................
----------------------------------------------------------------------
Ran 33 tests in 18.507s

OK
seastar memcached v1.0
exception in udp_server std::system_error (error system:103, Software caused connection abort)
exception in tcp_server std::system_error (error system:103, Software caused connection abort)exception in tcp_server 
std::system_error (error system:103, Software caused connection abort)
WARNING: debug mode. Not for benchmarking or production
INFO  2023-02-06 04:06:05,872 seastar - Reactor backend: linux-aio
WARN  2023-02-06 04:06:05,872 [shard 0] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
INFO  2023-02-06 04:06:05,875 [shard 0] seastar - Created fair group io-queue-0, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000
INFO  2023-02-06 04:06:05,875 [shard 0] seastar - IO queue uses 0.75ms latency goal for device 0
INFO  2023-02-06 04:06:05,875 [shard 0] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
INFO  2023-02-06 04:06:05,875 [shard 0] seastar - Created io queue dev(0) capacities: 512:2000:2000 1024:3000:3000 2048:5000:5000 4096:9000:9000 8192:17000:17000 16384:33000:33000 32768:65000:65000 65536:129000:129000 131072:257000:257000
WARN  2023-02-06 04:06:05,876 [shard 1] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
.......F...............
======================================================================
FAIL: test_expiry_at_epoch_time (__main__.TestCommands)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/apps/memcached/tests/test_memcached.py", line 51, in wrapper
    return f(self)
  File "/home/circleci/project/apps/memcached/tests/test_memcached.py", line 262, in test_expiry_at_epoch_time
    self.assertEqual(call('get key\r\n'), b'VALUE key 0 5\r\nhello\r\nEND\r\n')
AssertionError: b'END\r\n' != b'VALUE key 0 5\r\nhello\r\nEND\r\n'

----------------------------------------------------------------------
Ran 23 tests in 16.257s

FAILED (failures=1)
seastar memcached v1.0
exception in udp_server std::system_error (error system:103, Software caused connection abort)
exception in tcp_server std::system_error (error system:103, Software caused connection abort)
exception in tcp_server std::system_error (error system:103, Software caused connection abort)
Memcached started.
Running: /home/circleci/project/apps/memcached/tests/test_memcached.py
Killing memcached...
Memcached killed.
Memcached started.
Running: /home/circleci/project/apps/memcached/tests/test_memcached.py -U
Killing memcached...
Memcached killed.
Traceback (most recent call last):
  File "/home/circleci/project/apps/memcached/tests/test.py", line 49, in <module>
    run(args, ['-U'])
  File "/home/circleci/project/apps/memcached/tests/test.py", line 35, in run
    subprocess.check_call(cmdline)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/circleci/project/apps/memcached/tests/test_memcached.py', '-U']' returned non-zero exit status 1.
FAILED: apps/memcached/tests/CMakeFiles/app_memcached_test_memcached_run /home/circleci/project/build/debug/apps/memcached/tests/CMakeFiles/app_memcached_test_memcached_run 
cd /home/circleci/project/build/debug/apps/memcached/tests && /home/circleci/project/apps/memcached/tests/test.py --memcached /home/circleci/project/build/debug/apps/memcached/memcached
ninja: build stopped: subcommand failed.
```

see also https://app.circleci.com/pipelines/github/tchaikov/seastar/464/workflows/77d98198-b13d-48e2-8c8d-5259944d0efe/jobs/5560

**Comment by nyh** [comment]
I think this is a test bug. The failing test is:

```python
    def test_expiry_at_epoch_time(self):
        expiry = int(time.time()) + 1
        self.assertEqual(call('set key 0 %d 5\r\nhello\r\n' % expiry), b'STORED\
r\n')
        self.assertEqual(call('get key\r\n'), b'VALUE key 0 5\r\nhello\r\nEND\r\n')
        time.sleep(2)
        self.assertEqual(call('get key\r\n'), b'END\r\n')

```

It writes an item which should expire at the current time + 1, then reads and sees the item still exists, and then sleeps 2 seconds and checks the item is gone. In the test failure we're seeing, the item was gone immediately - before the 2-second sleep.

But I think "the current time + 1" is wrong: If we're one millisecond before the whole second, the "current time + 1" is just one millisecond away. It's very possible that when we read, we'll see the item gone!

Maybe we need to use "current time + 2", not +1?

By the way, does memcached's "set" really take absolute times, not relative time (e.g., "1" means expire the item 1 second later)? Did we ever run our test_memcached.py against the original memcached?

**Comment by tchaikov** [comment]
@nyh ahh, yeah. now i understand your explanation! it explains the failure better. thank you! and it's much more likely to happen than my "clock drift" theory.
