### ISSUE TITLE
Abort called when writing a temporary_buffer to a file_output_stream

### ISSUE THREAD

**Issue by nlescoua** [scylladb/seastar#1581]
When writing a temporary buffer to an output_streeam which is backed by a file_data_sink_impl, abort is called. 

(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339455040) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737339455040) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737339455040, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff74b0476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff74967f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555555598048 in seastar::file_data_sink_impl::put (this=<optimized out>, data=...) at /home/lescouarnecn/seastar/src/core/fstream.cc:365
#6  0x00005555555d768a in seastar::data_sink::put (this=<optimized out>, p=...) at /home/lescouarnecn/seastar/include/seastar/core/iostream.hh:157
#7  0x00005555555df981 in seastar::output_stream<char>::zero_copy_put (this=0x60100007bd30, p=...) at /usr/include/c++/12/bits/unique_ptr.h:189
#8  0x00005555555dfcd0 in seastar::output_stream<char>::zero_copy_split_and_put(seastar::net::packet)::{lambda()#1}::operator()() (__closure=__closure@entry=0x7ffff71f9270) at /usr/include/c++/12/bits/unique_ptr.h:189
#9  0x00005555555dff15 in seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::invoke<seastar::output_stream<char>::zero_copy_split_and_put(seastar::net::packet)::{lambda()#1}&>(seastar::output_stream<char>::zero_copy_split_and_put(seastar::net::packet)::{lambda()#1}&) (func=...) at /home/lescouarnecn/seastar/include/seastar/core/future.hh:2053
#10 seastar::repeat<seastar::output_stream<char>::zero_copy_split_and_put(seastar::net::packet)::{lambda()#1}>(seastar::output_stream<char>::zero_copy_split_and_put(seastar::net::packet)::{lambda()#1}&&) (action=...) at /home/lescouarnecn/seastar/include/seastar/core/loop.hh:122
#11 seastar::output_stream<char>::zero_copy_split_and_put (this=<optimized out>, p=...) at /home/lescouarnecn/seastar/include/seastar/core/iostream-impl.hh:109
#12 0x00005555555e0275 in seastar::output_stream<char>::write (this=this@entry=0x60100007bd30, p=...) at /usr/include/c++/12/tuple:454
#13 0x00005555555e043b in seastar::output_stream<char>::write (this=0x60100007bd30, p=...) at /home/lescouarnecn/seastar/include/seastar/core/iostream-impl.hh:146
#14 0x00005555555c987a in operator() (__closure=0x7ffff71f9460) at /home/lescouarnecn/seastar/tests/unit/fstream_test.cc:134
#15 0x00005555555c9cc2 in seastar::futurize<seastar::future<void> >::invoke<test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>::<lambda(seastar::shared_ptr<writer>)>::<lambda()> > (func=...) at /home/lescouarnecn/seastar/include/seastar/core/future.hh:2053
#16 seastar::futurize<seastar::future<void> >::invoke<test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>::<lambda(seastar::shared_ptr<writer>)>::<lambda()> > (func=...) at /home/lescouarnecn/seastar/include/seastar/core/future.hh:1904
#17 seastar::future<void>::then_impl<test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>::<lambda(seastar::shared_ptr<writer>)>::<lambda()> > (func=..., this=0x7ffff71f9450) at /home/lescouarnecn/seastar/include/seastar/core/future.hh:1528
#18 seastar::future<void>::then<test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>::<lambda(seastar::shared_ptr<writer>)>::<lambda()> > (func=..., this=0x7ffff71f9450) at /home/lescouarnecn/seastar/include/seastar/core/future.hh:1447
#19 operator() (__closure=0x7ffff71f95c0, w=...) at /home/lescouarnecn/seastar/tests/unit/fstream_test.cc:128
#20 0x00005555555ca313 in seastar::futurize<seastar::future<void> >::invoke<test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>::<lambda(seastar::shared_ptr<writer>)>, seastar::shared_ptr<writer> > (func=...) at /home/lescouarnecn/seastar/include/seastar/core/future.hh:2060
#21 seastar::future<seastar::shared_ptr<writer> >::then_impl<test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>::<lambda(seastar::shared_ptr<writer>)> > (func=..., this=0x7ffff71f95a0) at /home/lescouarnecn/seastar/include/seastar/core/future.hh:1528
#22 seastar::future<seastar::shared_ptr<writer> >::then<test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>::<lambda(seastar::shared_ptr<writer>)> > (func=..., this=0x7ffff71f95a0) at /home/lescouarnecn/seastar/include/seastar/core/future.hh:1447
#23 operator() (__closure=<optimized out>, f=...) at /home/lescouarnecn/seastar/tests/unit/fstream_test.cc:161
#24 0x00005555555cb6f5 in std::__invoke_impl<seastar::future<>, test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>&, seastar::file> (__f=...) at /usr/include/c++/12/bits/invoke.h:61
#25 std::__invoke<test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>&, seastar::file> (__fn=...) at /usr/include/c++/12/bits/invoke.h:97
#26 std::invoke<test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>&, seastar::file> (__fn=...) at /usr/include/c++/12/functional:111
#27 seastar::internal::future_invoke<test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>&, seastar::file> (v=..., func=...) at /home/lescouarnecn/seastar/include/seastar/core/future.hh:1202
#28 operator() (__closure=<optimized out>) at /home/lescouarnecn/seastar/include/seastar/core/future.hh:1509
#29 seastar::futurize<seastar::future<void> >::satisfy_with_result_of<seastar::future<seastar::file>::then_impl_nrvo<test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>, seastar::future<> >(test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>&&)::<lambda(pr_type&&, test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>&, seastar::future<seastar::file>::future_state&&)>::<lambda()> > (func=..., pr=...) at /home/lescouarnecn/seastar/include/seastar/core/future.hh:2045
#30 operator() (__closure=<optimized out>, state=..., func=..., pr=...) at /home/lescouarnecn/seastar/include/seastar/core/future.hh:1502
#31 seastar::continuation<seastar::internal::promise_base_with_type<void>, test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>, seastar::future<seastar::file>::then_impl_nrvo<test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>, seastar::future<> >(test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>&&)::<lambda(pr_type&&, test_fstream_zc::run_test_case() const::<lambda(seastar::tmp_dir&)>::<lambda(seastar::file)>&, seastar::future<seastar::file>::future_state&&)>, seastar::file>::run_and_dispose(void) (this=0x60105147f060) at /home/lescouarnecn/seastar/include/seastar/core/future.hh:779
#32 0x0000555555663478 in seastar::reactor::run_tasks (this=this@entry=0x60100012e000, tq=...) at /home/lescouarnecn/seastar/src/core/reactor.cc:2550
#33 0x0000555555663798 in seastar::reactor::run_some_tasks (this=this@entry=0x60100012e000) at /home/lescouarnecn/seastar/src/core/reactor.cc:2987
#34 0x000055555568b836 in seastar::reactor::run_some_tasks (this=0x60100012e000) at /home/lescouarnecn/seastar/include/seastar/core/circular_buffer_fixed_capacity.hh:209
#35 seastar::reactor::do_run (this=0x60100012e000) at /home/lescouarnecn/seastar/src/core/reactor.cc:3156
#36 0x000055555568c2ee in seastar::reactor::run (this=<optimized out>) at /home/lescouarnecn/seastar/src/core/reactor.cc:3039
#37 0x0000555555612ed4 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=0x7ffff71f9e60, ac=<optimized out>, av=0x7fffffffe4b8, func=...) at /home/lescouarnecn/seastar/include/seastar/core/reactor.hh:722
#38 0x0000555555613865 in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) (this=this@entry=0x7ffff71f9e60, ac=1, av=0x7fffffffe4b8, func=...) at /home/lescouarnecn/seastar/src/core/app-template.cc:156
#39 0x00005555555f3aa5 in operator() (__closure=0x55555587fde0) at /home/lescouarnecn/seastar/src/testing/test_runner.cc:75
#40 0x000055555564f222 in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/12/bits/std_function.h:591
#41 seastar::posix_thread::start_routine (arg=<optimized out>) at /home/lescouarnecn/seastar/src/core/posix.cc:73
#42 0x00007ffff7502b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#43 0x00007ffff7594a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

**Comment by xemul** [comment]
Not relevant in API level 9 (#3039)
