### ISSUE TITLE
seastar segfaults in tcp_test on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by tedqian** [scylladb/seastar#198]
Is there anything wrong or i made a mistake?

Following is what I get when I use gdb:

net::device::receive(std::function<future<> (net::packet)>) (this=0x6000000911c0, next_packet=...) at net/net.cc:251
251         auto sub = _queues[engine().cpu_id()]->_rx_stream.listen(std::move(next_packet));
(gdb) bt
#0  net::device::receive(std::function<future<> (net::packet)>) (this=0x6000000911c0, next_packet=...) at net/net.cc:251
#1  0x00000000004fcb33 in net::interface::interface (this=0x7fffffffd8f0, dev=std::shared_ptr (count 4892191, weak -1) 0x7fffffffd6b0) at net/net.cc:278
#2  0x000000000041331c in main (ac=<optimized out>, av=<optimized out>) at tcp_test.cc:62
(gdb) p local_engine
$1 = (reactor *) 0x0

**Comment by abc100m** [comment]
Had you solved this issue?
I have this issue on CentOS 7.2 too

**Comment by cooperpellaton** [comment]
Can confirm that this is still an issue.

Running the TCP_Test results in a segfault. Additionally when using this configuration for compilation: ./configure.py --mode="release" --compiler="g++-5" --cflags="-Wno-unused-variable -g" no debug files are created and GDB cannot be used to trace back the segfualt despite that fact that -g is enabled at compile time.

Running on Ubuntu 16.04 with CAF release 17.05.
