### ISSUE TITLE
Compiling with clang and mode sanitize needs additional `compiler-rt` dependency on Fedora

### ISSUE THREAD

**Issue by absporl** [scylladb/seastar#2559]
On Fedora 41 (also applies to 40), I ran into the following problem when trying to run the configure script:

```
$ seastar/configure.py --mode sanitize --without-tests --without-apps --without-demos --compiler clang++
-- The CXX compiler identification is Clang 19.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at cmake/SeastarDependencies.cmake:43 (find_package):
  Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
  --help-policy CMP0167" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:398 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Boost: /usr/include (found suitable version "1.83.0", minimum required is "1.73.0")
CMake Warning (dev) at cmake/SeastarDependencies.cmake:146 (find_package):
  Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
  --help-policy CMP0167" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:399 (seastar_find_dependencies)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found Boost: /usr/include (found suitable version "1.83.0", minimum required is "1.73.0") found components: filesystem program_options thread unit_test_framework chrono atomic
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.3.0")
-- Found c-ares: /usr/lib64/libcares.so (found suitable version "1.28.1", minimum required is "1.13")
-- Found lz4: /usr/lib64/liblz4.so (found suitable version "1.10.0", minimum required is "1.7.3")
-- Found GnuTLS: /usr/lib64/libgnutls.so (found suitable version "3.8.6", minimum required is "3.3.26")
-- Performing Test HAVE_IOURING_FEATURES
-- Performing Test HAVE_IOURING_FEATURES - Success
-- Found LibUring: //usr/lib64/liburing.so (found suitable version "2.6", minimum required is "2.0")
-- Performing Test LinuxMembarrier_FOUND
-- Performing Test LinuxMembarrier_FOUND - Success
-- Performing Test Sanitizers_SUPPORTED
-- Performing Test Sanitizers_SUPPORTED - Failed
-- Could NOT find Sanitizers (missing: Sanitizers_SUPPORTED) 
-- Performing Test CxxSourceLocation_SUPPORTED
-- Performing Test CxxSourceLocation_SUPPORTED - Success
-- Performing Test CxxSourceLocation_IMPLEMENTS_CWG2631
-- Performing Test CxxSourceLocation_IMPLEMENTS_CWG2631 - Success
-- Performing Test StdAtomic_EXPLICIT_LINK
-- Performing Test StdAtomic_EXPLICIT_LINK - Success
-- Found StdAtomic: -latomic
-- Found SystemTap-SDT: /usr/include
-- Found hwloc: /usr/lib64/libhwloc.so (Required is at least version "1.11.2")
-- Found lksctp-tools: /usr/lib64/libsctp.so
-- Found numactl: /usr/lib64/libnuma.so
-- Looking for getcontext
-- Looking for getcontext - found
-- Found yaml-cpp: /usr/lib64/libyaml-cpp.so (Required is at least version "0.5.1")
-- Found Protobuf: /usr/lib64/libprotobuf.so (found suitable version "3.19.6", minimum required is "2.5.0")
-- Found ragel: /usr/bin/ragel (found suitable version "7.0.4", minimum required is "6.10")
-- Looking for pthread_setname_np
-- Looking for pthread_setname_np - found
-- Found PthreadSetName: 1
-- Found Valgrind: /usr/include
-- Performing Test Cxx_Compiler_IMPLEMENTS_P2581R1
-- Performing Test Cxx_Compiler_IMPLEMENTS_P2581R1 - Failed
CMake Error at CMakeLists.txt:889 (message):
  Sanitizers not found!


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "seastar/configure.py", line 255, in <module>
    configure_mode(mode)
    ~~~~~~~~~~~~~~^^^^^^
  File "seastar/configure.py", line 251, in configure_mode
    subprocess.check_call(ARGS, shell=False, cwd=dir)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/subprocess.py", line 419, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-G', 'Ninja', '../..', '-DCMAKE_BUILD_TYPE=Sanitize', '-DCMAKE_CXX_COMPILER=clang++', '-DCMAKE_CXX_STANDARD=23', '-DCMAKE_CXX_COMPILER_LAUNCHER=', '-DCMAKE_INSTALL_PREFIX=/usr/local', '-DCMAKE_EXPORT_COMPILE_COMMANDS=no', '-DBUILD_SHARED_LIBS=no', '-DSeastar_API _LEVEL=7', '-DSeastar_SCHEDULING_GROUPS_COUNT=16', '-DSeastar_EXCLUDE_TESTS_FROM_ALL=yes', '-DSeastar_EXCLUDE_APPS_FROM_ALL=yes', '-DSeastar_EXCLUDE_DEMOS_FROM_ALL=yes', '-DSeastar_CXX_FLAGS=', '-DSeastar_LD_FLAGS=', '-DSeastar_MODULE=no', '-DSeastar_DPDK=no', '-DSeastar_DPDK_MACHINE=native', '-DSeastar_HWLOC=ye s', '-DSeastar_ALLOC_FAILURE_INJECTION=DEFAULT', '-DSeastar_TASK_BACKTRACE=no', '-DSeastar_ALLOC_PAGE_SIZE=no', '-DSeastar_SPLIT_DWARF=no', '-DSeastar_HEAP_PROFILING=no', '-DSeastar_DEFERRED_ACTION_REQUIRE_NOEXCEPT=yes', '-DSeastar_UNUSED_RESULT_ERROR=no', '-DSeastar_DEBUG_SHARED_PTR=default']' returned non-zero exit status 1.
```

After a lot of headaches, I figured out that the problem could be fixed by `dnf install compiler-rt` (**and removing the build directory**).

As a fix, maybe consider adding `compiler-rt` to the `install-dependencies.sh` script.

**Comment by tchaikov** [comment]
please note, `install-dependencies.sh` does not install clang at all. this script installs `g++`. if you specify `--compiler clang++` when configuring the building system , you might want to install the additional dependencies to build the tree.
