### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by adilbaig** [scylladb/seastar#436]
I followed the instructions here https://github.com/scylladb/seastar/blob/master/doc/building-docker.md

I git cloned the repo to `$HOME/workspace/seastar` and ran this

````
seabuild() { docker run -v $HOME/workspace/seastar/:/seastar -u $(id -u):$(id -g) -w /seastar -t seastar-dev "$@"; }

~/workspace/seastar$ seabuild ./configure.py
Notice: -fsanitize=vptr is broken, disabling; some debug mode tests are bypassed.
Notice: disabling -Wattributes due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80947
CMake Error: The current CMakeCache.txt directory /seastar/build/debug/fmt/CMakeCache.txt is different than the directory /home/adil/workspace/seastar/build/debug/fmt where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/seastar/fmt/CMakeLists.txt" does not match the source "/home/adil/workspace/seastar/fmt/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
Traceback (most recent call last):
  File "./configure.py", line 819, in <module>
    configure_fmt(mode, cxx=args.cxx, cc=args.cc)
  File "./configure.py", line 215, in configure_fmt
    subprocess.check_output(args=['cmake', '-G', 'Ninja', '../../../fmt', '-DCMAKE_CXX_COMPILER=' + cxx, '-DCMAKE_C_COMPILER=' + cc], cwd=builddir)
  File "/usr/lib64/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cmake', '-G', 'Ninja', '../../../fmt', '-DCMAKE_CXX_COMPILER=g++', '-DCMAKE_C_COMPILER=gcc']' returned non-zero exit status 1.


~/workspace/seastar$ seabuild ninja-build
[1/394] mkdir -p build/debug/c-ares && cd build/debug/c-ares && CC=gcc cmake -DCARES_STATIC=ON -DCARES_SHARED=OFF -DCMAKE_BUILD_TYPE=Debug /home/adil/workspace/seastar/c-ares
FAILED: build/debug/c-ares/Makefile 
mkdir -p build/debug/c-ares && cd build/debug/c-ares && CC=gcc cmake -DCARES_STATIC=ON -DCARES_SHARED=OFF -DCMAKE_BUILD_TYPE=Debug /home/adil/workspace/seastar/c-ares
CMake Error: The current CMakeCache.txt directory /seastar/build/debug/c-ares/CMakeCache.txt is different than the directory /home/adil/workspace/seastar/build/debug/c-ares where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source directory "/home/adil/workspace/seastar/c-ares" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
[3/394] /usr/bin/ninja -C build/debug/fmt
FAILED: build/debug/fmt/fmt/libfmt.a 
/usr/bin/ninja -C build/debug/fmt
ninja: Entering directory `build/debug/fmt'
[0/1] Re-running CMake...
CMake Error: The source directory "/home/adil/workspace/seastar/fmt" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
FAILED: build.ninja 
/usr/bin/cmake -H/home/adil/workspace/seastar/fmt -B/home/adil/workspace/seastar/build/debug/fmt
ninja: error: rebuilding 'build.ninja': subcommand failed
[6/394] SWAGGER build/debug/gen/apps/httpd/demo.json.hh
ninja: build stopped: subcommand failed.

````

**Comment by psankar** [comment]
Your `seabuild ./configure.py` step itself has failed. So you should not be running the `ninja-build` command at all.

I believe that you have some stale CMake artefacts from old incomplete builds with a broken cache. You can possibly run `rm -rf build` from your top-level git directory and redo `seabuild ./configure.py` . Also, did you run `git submodule update --init`  after git clone of seastar sources ? Because your source directory should contain `fmt`, `c-ares`, `dpdk` in the top-level,  which is also not detected (as per the second command's log).

**Comment by denesb** [comment]
> CMake Error: The source directory "/home/adil/workspace/seastar/fmt" does not exist.

Did you run `git submodule update --init --recursive` after cloning the project?

**Comment by hakuch** [comment]
@adilbaig, if you run `./configure.py` (which populates the `build` directory) outside of Docker (in your native file-system and OS) and then run the `seabuild` script as directed, you'll get the error you describe.

The issue is that the `build` directory is mounted inside the container at `/seastar/build` with paths that CMake doesn't expect to find.

The fix, as @psankar suggested, is to delete the `build` directory in your host and run `seabuild` again.

In general, I don't think it's possible to compile to the same directory from both the host and inside the container.
