### ISSUE TITLE
segfault running integration tests

### ISSUE THREAD

**Issue by noahdesu** [scylladb/seastar#594]
hitting a segfault in master running integration test `sudo build/src/integration_tests/smf_rpc_integration_test`

```
Thread 1 (Thread 0x7effd66faf40 (LWP 31094)):
#0  0x0000000000000001 in ?? ()
#1  0x00000000005c51c1 in seastar::reactor::run_tasks(seastar::reactor::task_queue&) ()
#2  0x00000000005c54b0 in seastar::reactor::run_some_tasks() [clone .part.2977] ()
#3  0x0000000000616636 in seastar::reactor::run() ()
#4  0x0000000000581d62 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) ()
#5  0x00000000005826f7 in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) ()
#6  0x00000000004db1c7 in main ()
```

Also note that this doesn't seem to be deterministic. Outside of GDB the run succeeded once, inside GDB I need to `set disable-randomization off` in order to get reliable reproduction of the fault.

**Comment by noahdesu** [comment]
sorry! wrong project :P
