### ISSUE TITLE
Segmentation fault in debug mode, before main() is called

### ISSUE THREAD

**Issue by denesb** [scylladb/seastar#599]
```
Starting program: /home/alex/develop/scyllatest/build/scyllatest
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff522f774 in __once_proxy () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff6764827 in __pthread_once_slow (once_control=0x555555aa058c <seastar::memory::mem_base()::flag>, init_routine=0x7ffff522f760 <__once_proxy>) at pthread_once.c:116
#3  0x00005555556133ae in __gthread_once (__func=<optimized out>, __once=0x555555aa058c <seastar::memory::mem_base()::flag>) at /usr/include/x86_64-linux-gnu/c++/7/bits/gthr-default.h:699
#4  std::call_once<seastar::memory::mem_base()::<lambda()> > (__once=..., __f=...) at /usr/include/c++/7/mutex:684
#5  seastar::memory::mem_base () at ../../src/core/memory.cc:198
#6  seastar::memory::cpu_pages::initialize (this=this@entry=0x7ffff7fa6880) at ../../src/core/memory.cc:877
#7  0x000055555561352e in seastar::memory::cpu_pages::initialize (this=0x7ffff7fa6880) at ../../src/core/memory.cc:871
#8  seastar::memory::cpu_pages::find_and_unlink_span (this=this@entry=0x7ffff7fa6880, n_pages=n_pages@entry=1) at ../../src/core/memory.cc:552
#9  0x0000555555613b2c in seastar::memory::cpu_pages::find_and_unlink_span_reclaiming (this=this@entry=0x7ffff7fa6880, n_pages=n_pages@entry=1) at ../../src/core/memory.cc:566
#10 0x0000555555614338 in seastar::memory::cpu_pages::allocate_large_and_trim (this=this@entry=0x7ffff7fa6880, n_pages=1) at ../../src/core/memory.cc:593
#11 0x000055555561442d in seastar::memory::cpu_pages::allocate_large (this=this@entry=0x7ffff7fa6880, n_pages=n_pages@entry=1) at ../../src/core/memory.cc:639
#12 0x000055555561476d in seastar::memory::small_pool::add_more_objects (this=0x7ffff7fa6db0) at ../../src/core/memory.cc:1145
#13 0x0000555555614855 in seastar::memory::small_pool::allocate (this=0x7ffff7fa6db0) at ../../src/core/memory.cc:1105
#14 0x0000555555615c1c in seastar::memory::allocate (size=<optimized out>, size@entry=32) at ../../src/core/memory.cc:1256
#15 0x0000555555615ce3 in malloc (n=<optimized out>) at ../../src/core/memory.cc:1504
#16 calloc (nmemb=nmemb@entry=1, size=size@entry=32) at ../../src/core/memory.cc:1535
#17 0x00007ffff3aee7c2 in __cxa_thread_atexit_impl (func=0x555555614bc0 <seastar::memory::cpu_pages::~cpu_pages()>, obj=0x7ffff7fa6880, dso_symbol=0x555555a9f008) at cxa_thread_atexit_impl.c:106
#18 0x0000555555615c81 in seastar::memory::<lambda()>::operator() (__closure=<optimized out>) at ../../src/core/memory.cc:456
#19 seastar::memory::get_cpu_mem () at ../../src/core/memory.cc:1244
#20 seastar::memory::allocate (size=<optimized out>, size@entry=32) at ../../src/core/memory.cc:1256
#21 0x0000555555615ce3 in malloc (n=<optimized out>) at ../../src/core/memory.cc:1504
---Type <return> to continue, or q <return> to quit---
#22 calloc (nmemb=nmemb@entry=1, size=size@entry=32) at ../../src/core/memory.cc:1535
#23 0x00007ffff5fd67e5 in _dlerror_run (operate=operate@entry=0x7ffff5fd60d0 <dlsym_doit>, args=args@entry=0x7fffffffdc50) at dlerror.c:140
#24 0x00007ffff5fd6166 in __dlsym (handle=handle@entry=0xffffffffffffffff, name=name@entry=0x55555581e52d "dl_iterate_phdr") at dlsym.c:70
#25 0x0000555555780ae3 in seastar::<lambda()>::operator() (__closure=<optimized out>) at ../../src/core/exception_hacks.cc:70
#26 seastar::dl_iterate_phdr_org () at ../../src/core/exception_hacks.cc:73
#27 0x0000555555780d25 in dl_iterate_phdr (callback=0x7ffff6ef84e0, data=0x7fffffffdd40) at ../../src/core/exception_hacks.cc:113
#28 0x00007ffff6ef85cc in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
#29 0x00007ffff6f06479 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
#30 0x00007ffff7de5806 in _dl_init (main_map=0x7ffff7ffe170, argc=1, argv=0x7fffffffde08, env=0x7fffffffde18) at dl-init.c:104
#31 0x00007ffff7dd60ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#32 0x0000000000000001 in ?? ()
#33 0x00007fffffffe151 in ?? ()
#34 0x0000000000000000 in ?? ()
(gdb) info register
rax            0x7ffff7382c18   140737341041688
rbx            0x555555aa058c   93824997787020
rcx            0x555555612f80   93824993013632
rdx            0x555555aa058c   93824997787020
rsi            0x7ffff6764880   140737328334976
rdi            0x7ffff54f57b8   140737309005752
rbp            0x7ffff522f760   0x7ffff522f760 <__once_proxy>
rsp            0x7fffffffd9e8   0x7fffffffd9e8
r8             0xca     202
r9             0x1      1
r10            0x13     19
r11            0x7ffff6e52900   140737335601408
r12            0x7fffffffda00   140737488345600
r13            0x1      1
r14            0x7ffff7fa7a40   140737353775680
r15            0x1      1
rip            0x0      0x0
eflags         0x10202  [ IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
---Type <return> to continue, or q <return> to quit---
fs             0x0      0
gs             0x0      0
(gdb) info frame
Stack level 0, frame at 0x7fffffffd9f0:
 rip = 0x0; saved rip = 0x7ffff522f774
 called by frame at 0x7fffffffda00
 Arglist at 0x7fffffffd9e0, args:
 Locals at 0x7fffffffd9e0, Previous frame's sp is 0x7fffffffd9f0
 Saved registers:
  rip at 0x7fffffffd9e8
```

**Comment by denesb** [comment]
Ubuntu (Kubuntu) 18.04
GCC 7.3.0

**Comment by arrabyte** [comment]
The issue occur just including  <seastar/core/reactor.hh>

#include <seastar/core/reactor.hh>
int main(int argc, char** argv) { return 0; }

**Comment by denesb** [comment]
Turns out this is caused by compiling the application in debug mode (including any included seastar code from the headers) and then linking with release seastar library. As we have code, compiled conditionally on the build mode, failures such as this are expected in this case.
