### ISSUE TITLE
dns_test times out

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/seastar#626]
It seems to be blocking the reactor inside do_recvfrom():

```
...
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Release socket 1 -> 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1. 16 bytes sent.
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Poll sockets
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 rw/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1(1)
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1 unavailable.
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 r/
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Release socket 1 -> 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Send 1. 1 bytes sent.
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Poll sockets
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - fd 1 r/w
TRACE 2019-04-03 14:14:05,875 [shard 0] dns_resolver - Release socket 1 -> 1
TRACE 2019-04-03 14:14:07,885 [shard 0] dns_resolver - Read 1 -> 0 bytes
TRACE 2019-04-03 14:14:07,885 [shard 0] dns_resolver - Poll sockets
TRACE 2019-04-03 14:14:07,885 [shard 0] dns_resolver - ares_fds: 2
TRACE 2019-04-03 14:14:07,885 [shard 0] dns_resolver - fd 1 r/rw
TRACE 2019-04-03 14:14:07,885 [shard 0] dns_resolver - Read 1(1)
Reactor stalled for 2602 ms on shard 0.
Backtrace:
  0x00000000004943fe
  0x0000000000453209
  0x0000000000453488
  0x00000000004534a5
  0x00000000004534bd
  0x00000000004534e4
  0x00007efe77dac02f
  0x000000000050d0ef
  0x000000000050d5c0
  0x000000000050e13c
  /lib64/libcares.so.2+0x000000000000aed3
  0x00007efe77d916d3
  0x0000000000500def
  0x0000000000504b6c
  0x000000000050124a
  0x000000000051812b
  0x000000000044fe4f
  0x00000000004549ad
  0x0000000000481620
  0x000000000042af02
  0x0000000000427645
  0x00000000004279e0
  0x000000000044bf33
  /lib64/libpthread.so.0+0x000000000000858d
  /lib64/libc.so.6+0x00000000000fd6a2
Reactor stalled for 7207 ms on shard 0.
Backtrace:
  0x00000000004943fe
  0x0000000000453209
  0x0000000000453488
  0x00000000004534a5
  0x00000000004534bd
  0x00000000004534e4
  0x00007efe77dac02f
  0x0000000000503526
  0x000000000050d8df
  0x000000000050e13c
  /lib64/libcares.so.2+0x000000000000aed3
  0x00007efe77d916d3
  0x0000000000500def
  0x0000000000504b6c
  0x000000000050124a
  0x000000000051812b
  0x000000000044fe4f
  0x00000000004549ad
  0x0000000000481620
  0x000000000042af02
  0x0000000000427645
  0x00000000004279e0
  0x000000000044bf33
  /lib64/libpthread.so.0+0x000000000000858d
  /lib64/libc.so.6+0x00000000000fd6a2
Reactor stalled for 15814 ms on shard 0.
Backtrace:
  0x00000000004943fe
  0x0000000000453209
  0x0000000000453488
  0x00000000004534a5
  0x00000000004534bd
  0x00000000004534e4
  0x00007efe77dac02f
  0x0000000000503471
  0x000000000050d8df
  0x000000000050e13c
  /lib64/libcares.so.2+0x000000000000aed3
  0x00007efe77d916d3
  0x0000000000500def
  0x0000000000504b6c
  0x000000000050124a
  0x000000000051812b
  0x000000000044fe4f
  0x00000000004549ad
  0x0000000000481620
  0x000000000042af02
  0x0000000000427645
  0x00000000004279e0
  0x000000000044bf33
  /lib64/libpthread.so.0+0x000000000000858d
  /lib64/libc.so.6+0x00000000000fd6a2
Reactor stalled for 32430 ms on shard 0.
Backtrace:
  0x00000000004943fe
  0x0000000000453209
  0x0000000000453488
  0x00000000004534a5
  0x00000000004534bd
  0x00000000004534e4
  0x00007efe77dac02f
  0x000000000041a70f
  0x0000000000503526
  0x000000000050d8df
  0x000000000050e13c
  /lib64/libcares.so.2+0x000000000000aed3
  0x00007efe77d916d3
  0x0000000000500def
  0x0000000000504b6c
  0x000000000050124a
  0x000000000051812b
  0x000000000044fe4f
  0x00000000004549ad
  0x0000000000481620
  0x000000000042af02
  0x0000000000427645
  0x00000000004279e0
  0x000000000044bf33
  /lib64/libpthread.so.0+0x000000000000858d
  /lib64/libc.so.6+0x00000000000fd6a2
Reactor stalled for 65061 ms on shard 0.
Backtrace:
  0x00000000004943fe
  0x0000000000453209
  0x0000000000453488
  0x00000000004534a5
  0x00000000004534bd
  0x00000000004534e4
  0x00007efe77dac02f
  0x0000000000503526
  0x000000000050d8df
  0x000000000050e13c
  /lib64/libcares.so.2+0x000000000000aed3
  0x00007efe77d916d3
  0x0000000000500def
  0x0000000000504b6c
  0x000000000050124a
  0x000000000051812b
  0x000000000044fe4f
  0x00000000004549ad
  0x0000000000481620
  0x000000000042af02
  0x0000000000427645
  0x00000000004279e0
  0x000000000044bf33
  /lib64/libpthread.so.0+0x000000000000858d
  /lib64/libc.so.6+0x00000000000fd6a2
```

```
(gdb) bt
#0  0x000000000050d110 in seastar::input_stream<char>::read_up_to(unsigned long) ()
#1  0x000000000050d5c1 in seastar::net::dns_resolver::impl::do_recvfrom(int, void*, unsigned long, int, sockaddr*, unsigned int*) ()
#2  0x000000000050e13d in seastar::net::dns_resolver::impl::impl(seastar::network_stack&, seastar::net::dns_resolver::options const&)::{lambda(int, void*, unsigned long, int, sockaddr*, unsigned int*, void*)#7}::_FUN(int, void*, unsigned long, int, sockaddr*, unsigned int*, void*) ()
#3  0x00007fc8b5ffced4 in socket_recv.isra () from /lib64/libcares.so.2
#4  0x00007fc8b5ffe6d4 in processfds () from /lib64/libcares.so.2
#5  0x0000000000500df0 in seastar::net::dns_resolver::impl::poll_sockets() ()
#6  0x0000000000504b6d in seastar::noncopyable_function<seastar::future<> (seastar::future<seastar::temporary_buffer<char> >)>::direct_vtable_for<seastar::future<seastar::temporary_buffer<char> >::then_wrapped<seastar::net::dns_resolver::impl::do_recvfrom(int, void*, unsigned long, int, sockaddr*, unsigned int*)::{lambda(seastar::future<seastar::temporary_buffer<char> >)#1}, seastar::future<> >(seastar::net::dns_resolver::impl::do_recvfrom(int, void*, unsigned long, int, sockaddr*, unsigned int*)::{lambda(seastar::future<seastar::temporary_buffer<char> >)#1}&&)::{lambda(seastar::future<seastar::temporary_buffer<char> >)#1}>::call(seastar::noncopyable_function<seastar::future<> (seastar::future<seastar::temporary_buffer<char> >)> const*, seastar::future<seastar::temporary_buffer<char> >) ()
#7  0x000000000050124b in seastar::future<> seastar::futurize<seastar::future<> >::apply<seastar::noncopyable_function<seastar::future<> (seastar::future<seastar::temporary_buffer<char> >)>, seastar::future<seastar::temporary_buffer<char> > >(seastar::noncopyable_function<seastar::future<> (seastar::future<seastar::temporary_buffer<char> >)>&&, seastar::future<seastar::temporary_buffer<char> >&&) ()
#8  0x000000000051812c in seastar::continuation<seastar::future<seastar::temporary_buffer<char> >::then_wrapped_impl<seastar::noncopyable_function<seastar::future<> (seastar::future<seastar::temporary_buffer<char> >)>, seastar::future<> >(seastar::noncopyable_function<seastar::future<> (seastar::future<seastar::temporary_buffer<char> >)>&&)::{lambda(auto:1&&)#1}, seastar::temporary_buffer<char> >::run_and_dispose() ()
#9  0x000000000044fe50 in seastar::reactor::run_tasks(seastar::reactor::task_queue&) ()
#10 0x00000000004549ae in seastar::reactor::run_some_tasks() ()
#11 0x0000000000481621 in seastar::reactor::run() ()
#12 0x000000000042af03 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) ()
#13 0x0000000000427646 in seastar::testing::test_runner::start(int, char**)::{lambda()#1}::operator()() ()
#14 0x00000000004279e1 in std::_Function_handler<void (), seastar::testing::test_runner::start(int, char**)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#15 0x000000000044bf34 in seastar::posix_thread::start_routine(void*) ()
#16 0x00007fc8b600e58e in start_thread () from /lib64/libpthread.so.0
#17 0x00007fc8b564f6a3 in clone () from /lib64/libc.so.6
```

**Comment by travisdowns** [comment]
Highly likely fixed in https://github.com/scylladb/seastar/pull/3699.

The backtrace is the exact one which occurs when that issue triggers. So probably fixed, or also gone due to rewrites to this code in the intervening 7 years.
