### ISSUE TITLE
Unit tests crash when given an unrecognized option

### ISSUE THREAD

**Issue by bhalevy** [scylladb/seastar#673]
```
$ build/release/tests/unit/alloc_test -- --foo
error: unrecognised option '--foo'

Try --help.
Segmentation fault (core dumped)

$ gdb -c alloc_test.7923.1565789015.core build/release/tests/unit/alloc_test
GNU gdb (GDB) Fedora 8.2-7.fc29
...
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `build/release/tests/unit/alloc_test -- --foo'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f66fbc1d1f3 in munmap () from /lib64/libc.so.6
...
(gdb) info threads
  Id   Target Id         Frame 
* 1    LWP 7924          0x00007f66fbc1d1f3 in munmap () from /lib64/libc.so.6
  2    LWP 7923          0x00007f66fc5e872c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f66fbc1d1f3 in munmap () from /lib64/libc.so.6
Backtrace stopped: Cannot access memory at address 0x7f66fb7fd998
(gdb) thread 2
[Switching to thread 2 (LWP 7923)]
#0  0x00007f66fc5e872c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f66fc5e872c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f66fbf496f0 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
#2  0x0000000000438b6d in std::condition_variable::wait<seastar::testing::exchanger<std::__exception_ptr::exception_ptr>::take()::{lambda()#1}>(std::unique_lock<std::mutex>&, seastar::testing::exchanger<std::__exception_ptr::exception_ptr>::take()::{lambda()#1}) (__p=..., 
    __lock=..., this=0x7ffc1b663018) at /usr/include/c++/8/bits/exception_ptr.h:145
#3  seastar::testing::exchanger<std::__exception_ptr::exception_ptr>::take (this=0x7ffc1b662ff0) at ../../include/seastar/testing/exchanger.hh:69
#4  seastar::testing::test_runner::run_sync(std::function<seastar::future<> ()>) (this=0x651560 <seastar::testing::instance>, task=...) at ../../src/testing/test_runner.cc:117
#5  0x0000000000437be6 in seastar::testing::seastar_test::run (this=0x651518 <alloc_almost_all_and_realloc_it_with_a_smaller_size_instance>) at /usr/include/c++/8/new:169
#6  0x00007f66fc72fba2 in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) () from /lib64/libboost_unit_test_framework.so.1.66.0
#7  0x00007f66fc72f78d in boost::execution_monitor::catch_signals(boost::function<int ()> const&) () from /lib64/libboost_unit_test_framework.so.1.66.0
#8  0x00007f66fc72f865 in boost::execution_monitor::execute(boost::function<int ()> const&) () from /lib64/libboost_unit_test_framework.so.1.66.0
#9  0x00007f66fc72f941 in boost::execution_monitor::vexecute(boost::function<void ()> const&) () from /lib64/libboost_unit_test_framework.so.1.66.0
#10 0x00007f66fc755c89 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) () from /lib64/libboost_unit_test_framework.so.1.66.0
#11 0x00007f66fc73ba97 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) () from /lib64/libboost_unit_test_framework.so.1.66.0
#12 0x00007f66fc73bcc0 in boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) () from /lib64/libboost_unit_test_framework.so.1.66.0
#13 0x00007f66fc7343b9 in boost::unit_test::framework::run(unsigned long, bool) () from /lib64/libboost_unit_test_framework.so.1.66.0
#14 0x00007f66fc753648 in boost::unit_test::unit_test_main(bool (*)(), int, char**) () from /lib64/libboost_unit_test_framework.so.1.66.0
#15 0x0000000000437880 in seastar::testing::entry_point (argc=<optimized out>, argv=<optimized out>) at ../../src/testing/entry_point.cc:50
#16 0x00007f66fbb49413 in __libc_start_main () from /lib64/libc.so.6
#17 0x000000000042df8e in _start () at /usr/include/boost/test/tree/observer.hpp:40
```

**Comment by denesb** [comment]
This was recently fixed for non test seastar executables, but I can't remember the issue #, or the commit that fixed it.

**Comment by denesb** [comment]
I think this is the commit I was remembering: https://github.com/scylladb/seastar/commit/27d763b613691147556b4cef25822b4d8ff42dad. Looks like this should have fixed the issue for the tests as well, so this is most likely something else.

**Comment by bhalevy** [comment]
@denesb yeah, it's a different issue.  bfa444e3cc2854a35ce84526b763d89174f9ad6c fixes the issue in seastar and I'm now testing it with scylla unit tests as well.
