### ISSUE TITLE
crash in test_self_move with --c++-dialect=gnu++14 in dev mode

### ISSUE THREAD

**Issue by bhalevy** [scylladb/seastar#741]
Seastar version 8fae03c22d39bab3cc71189b4cc36a14f1f8c5e3
g++ (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Fedora release 31 (Thirty One)
```
$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c8f1187e..94b6d603 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -71,7 +71,7 @@ set_property (CACHE Seastar_API_LEVEL
 #
 
 set (CMAKE_CXX_FLAGS_DEV
-  "-O1"
+  "-O1 -g"
   CACHE
   STRING
   "Flags used by the C++ compiler during dev builds."

$ ./configure.py --c++-dialect gnu++14 --mode=dev
```

```
$ ninja -C build/dev tests/unit/futures_test && build/dev/tests/unit/futures_test -l all -t test_self_move -- -c2
random-seed=2771770227
Running 1 test case...
Entering test module "../../tests/unit/futures_test.cc"
../../tests/unit/futures_test.cc(0): Entering test case "test_self_move"
../../src/testing/seastar_test.cc(39): info: check true has passed
../../tests/unit/futures_test.cc(61): info: check *std::get<0>(std::move(s2).get()) == 42 has passed
../../tests/unit/futures_test.cc(70): info: check *p2.get_future().get0() == 42 has passed
unknown location(0): fatal error: in "test_self_move": signal: SIGSEGV, si_code: 0 (memory access violation at address: 0x00000080)
../../tests/unit/futures_test.cc(70): last checkpoint
Test is aborted
../../tests/unit/futures_test.cc(0): Leaving test case "test_self_move"; testing time: 268us
Test is aborted
Leaving test module "../../tests/unit/futures_test.cc"; testing time: 288us

*** 1 failure is detected in the test module "../../tests/unit/futures_test.cc"
Segmentation fault (core dumped)
```

**Comment by bhalevy** [comment]
Core dump and test binary uploaded to google cloud:
```
$ gsutil ls gs://scratch.scylladb.com/issues/seastar/741/
gs://scratch.scylladb.com/issues/seastar/741/futures_test.688844.1588004666.core.gz
gs://scratch.scylladb.com/issues/seastar/741/futures_test.gz
```

**Comment by bhalevy** [comment]
I reproduced this at 8fae03c22d39bab3cc71189b4cc36a14f1f8c5e3 under scylla dbuild with with scylladb/scylla@bf5f247bc511b4e7240236eb307d3be4b0d69656
```
$ cat tools/toolchain/image 
docker.io/scylladb/scylla-toolchain:fedora-31-20200427
```
and uploaded `gs://scratch.scylladb.com/issues/seastar/741/futures_test.927.1588590147.core.gz`

```
(gdb) bt
#0  0x00007f249202068d in _dl_fixup () from /lib64/ld-linux-x86-64.so.2
#1  0x00007f249202778e in _dl_runtime_resolve_xsavec () from /lib64/ld-linux-x86-64.so.2
#2  0x00000000004738ee in seastar::testing::exchanger<bool>::~exchanger (this=0x600000090d90, __in_chrg=<optimized out>) at ../../include/seastar/testing/exchanger.hh:34
#3  __gnu_cxx::new_allocator<seastar::testing::exchanger<bool> >::destroy<seastar::testing::exchanger<bool> > (__p=0x600000090d90, this=0x600000090d90) at /usr/include/c++/9/ext/new_allocator.h:153
#4  std::allocator_traits<std::allocator<seastar::testing::exchanger<bool> > >::destroy<seastar::testing::exchanger<bool> > (__p=0x600000090d90, __a=...) at /usr/include/c++/9/bits/alloc_traits.h:497
#5  std::_Sp_counted_ptr_inplace<seastar::testing::exchanger<bool>, std::allocator<seastar::testing::exchanger<bool> >, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x600000090d80) at /usr/include/c++/9/bits/shared_ptr_base.h:557
#6  0x00000000004769b3 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x600000090d80) at /usr/include/c++/9/ext/atomicity.h:69
#7  0x000000000047019b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x600000140c28, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#8  std::__shared_ptr<seastar::testing::exchanger<bool>, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x600000140c20, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#9  std::shared_ptr<seastar::testing::exchanger<bool> >::~shared_ptr (this=0x600000140c20, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr.h:103
#10 seastar::testing::test_runner::<lambda()>::~<lambda> (this=0x600000140c08, __in_chrg=<optimized out>) at ../../src/testing/test_runner.cc:65
#11 std::_Function_base::_Base_manager<seastar::testing::test_runner::start(int, char**)::<lambda()> >::_M_destroy (__victim=...) at /usr/include/c++/9/bits/std_function.h:191
#12 std::_Function_base::_Base_manager<seastar::testing::test_runner::start(int, char**)::<lambda()> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation) (__dest=..., __source=..., __op=<optimized out>) at /usr/include/c++/9/bits/std_function.h:215
#13 0x0000000000497790 in std::_Function_base::~_Function_base (this=0x600000081f60, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/std_function.h:260
#14 std::function<void ()>::~function() (this=0x600000081f60, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/std_function.h:369
#15 std::default_delete<std::function<void ()> >::operator()(std::function<void ()>*) const (__ptr=0x600000081f60, this=<optimized out>) at /usr/include/c++/9/bits/unique_ptr.h:81
#16 std::unique_ptr<std::function<void ()>, std::default_delete<std::function<void ()> > >::~unique_ptr() (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/unique_ptr.h:292
#17 seastar::posix_thread::~posix_thread (this=<optimized out>, __in_chrg=<optimized out>) at ../../src/core/posix.cc:108
#18 0x0000000000470311 in std::default_delete<seastar::posix_thread>::operator() (__ptr=0x600000140bb8, this=0x678900 <seastar::testing::instance>) at /usr/include/c++/9/bits/unique_ptr.h:75
#19 std::unique_ptr<seastar::posix_thread, std::default_delete<seastar::posix_thread> >::reset (__p=0x600000140bb8, this=0x678900 <seastar::testing::instance>) at /usr/include/c++/9/bits/unique_ptr.h:402
#20 std::unique_ptr<seastar::posix_thread, std::default_delete<seastar::posix_thread> >::operator=(decltype(nullptr)) (this=0x678900 <seastar::testing::instance>) at /usr/include/c++/9/bits/unique_ptr.h:336
#21 seastar::testing::test_runner::finalize (this=0x678900 <seastar::testing::instance>) at ../../src/testing/test_runner.cc:140
#22 0x000000000046f0f2 in seastar::testing::entry_point (argc=<optimized out>, argv=<optimized out>) at ../../src/testing/entry_point.cc:52
#23 0x000000000041d7f4 in main (argc=<optimized out>, argv=<optimized out>) at ../../include/seastar/testing/seastar_test.hh:65
```

**Comment by bhalevy** [comment]
@espindola: fyi, I cannot reproduce this crash with 3c2e2781195b3e2b786970f4f62c639d5b706eb9 and on.
