### ISSUE TITLE
demo program crashed

### ISSUE THREAD

**Issue by balusch** [scylladb/seastar#872]
I tried to learn and use seastar, but the echo_demo crashed whenever I ran it:

```sh
% sudo ./echo_demo
[sudo] password for balusch:
../../include/seastar/core/reactor.hh:743:13: runtime error: reference binding to null pointer of type 'struct reactor'
../../src/core/reactor.cc:3012:22: runtime error: member call on null pointer of type 'struct reactor'
../../include/seastar/core/reactor.hh:567:38: runtime error: member access within null pointer of type 'struct reactor'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==542096==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000015f8 (pc 0x5599449caacc bp 0x7ffd9aee9360 sp 0x7ffd9aee9260 T0)
==542096==The signal is caused by a READ memory access.
    #0 0x5599449caacc in seastar::reactor::add_task(seastar::task*) (/study/Workspace/SeaStar/code/build/debug/demos/echo_demo+0x2979acc)
    #1 0x5599448da9e1 in seastar::internal::poller::do_register() ../../src/core/reactor.cc:3012
    #2 0x5599449ca6b3 in seastar::internal::poller::poller(std::unique_ptr<seastar::pollfn, std::default_delete<seastar::pollfn> >) ../../include/seastar/core/reactor.hh:165
    #3 0x559944ef77c6 in simple<seastar::net::qp::qp(bool, std::string, uint8_t)::<lambda()> > ../../include/seastar/core/reactor.hh:161
    #4 0x559944ee8ce4 in seastar::net::qp::qp(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned char) ../../src/net/net.cc:113
    #5 0x5599450c59ca in seastar::virtio::qp::qp(seastar::virtio::device*, unsigned long, unsigned long) ../../src/net/virtio.cc:762
    #6 0x5599450c747f in seastar::virtio::qp_vhost::qp_vhost(seastar::virtio::device*, boost::program_options::variables_map) ../../src/net/virtio.cc:824
    #7 0x5599450e0f4f in std::_MakeUniq<seastar::virtio::qp_vhost>::__single_object std::make_unique<seastar::virtio::qp_vhost, seastar::virtio::device*, boost::program_options::variables_map&>(seastar::virtio::device*&&, boost::program_options::variables_map&) /usr/include/c++/10.2.0/bits/unique_ptr.h:962
    #8 0x5599450ca9c4 in seastar::virtio::device::init_local_queue(boost::program_options::variables_map, unsigned short) ../../src/net/virtio.cc:990
    #9 0x5599447ce28e in main ../../demos/echo_demo.cc:115
    #10 0x7f633457eb24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
    #11 0x5599447cbf1d in _start (/study/Workspace/SeaStar/code/build/debug/demos/echo_demo+0x277af1d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/study/Workspace/SeaStar/code/build/debug/demos/echo_demo+0x2979acc) in seastar::reactor::add_task(seastar::task*)
==542096==ABORTING
```

​Jump into the code and I find `local_engine` haven't been initialized while calling member function `init_local_queue`, where  `local_engine` is used to add task to its circular_buffer. And I find that  `local_engine` is only initialized in `smp::configure` which is not called by the demo program,  is it a bug or I just missed something? 

The way I compiled and installed the project:

```sh
% ./configure.py --mode=debug --cflags='-g -O0'
% ninja -C build/debug
% sudo make install
```

And I haven't changed any thing of the demo program.

**Comment by jeffRTC** [comment]
@avikivity Here we are. This is the exact problem I'm seeing.  So, is this an actual bug of Seastar now?

**Comment by jeffRTC** [comment]
@balusch Have you found any solution for this?
